spring:
  application:
    name: catalog-service
  profiles:
    active: develop
  data:
    mongodb:
      host: mongo-eshop
      port: 27017
      database: test
server:
  port: 8080
ribbon:
    eureka:
        enabled: true
