spring:
  application:
    name: vacancies-service
  profiles:
    active: develop
  data:
    mongodb:
      host: 192.168.179.130
      port: 27017
      database: test
server:
  port: 8080
  
ribbon:
    eureka:
        enabled: true
